name: Docker w Vulnerable App concurrency

on:
  workflow_dispatch: 

permissions: 
  contents: read
  issues: write
  pull-requests: write

jobs:
  docker-setup:
    name: Docker Compose 
    runs-on: ubuntu-latest

    steps:
    - name: Docker Setup 
      uses: docker/setup-docker-action@v5

    - name: Docker pull and run
      run: "docker pull bkimminich/juice-shop && docker run --rm -d -p 3000:3000 bkimminich/juice-shop" 

    - name: ZAP Baseline Scan
      id: scan-zap
      uses: zaproxy/action-baseline@de8ad967d3548d44ef623df22cf95c3b0baf8b25
      with:
        # GitHub Token to create issues in the repository
        token: ${{ secrets.GITHUBB_REPO_TOKEN }}
        # Target URL
        target: http://localhost:3000
        issue_title: ZAP issue report
        # The action status will be set to fail if ZAP identifies any alerts during the baseline scan
        artifact_name: Zap-results


    - name: Parse JSON to be sent
      id: parse-json
      run: |
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        {
          echo "remediation_body<<$EOF"
          jq -r '.site[]?.alerts[]? | "### 🛠️ " + .name + "\n**How to Fix:**\n" + .solution + "\n\n---"' report_json.json
          echo "$EOF"
        } >> $GITHUB_OUTPUT

    - name: Update the GitHub issue board
      env:
        GH_TOKEN: ${{ secrets.GITHUBB_REPO_TOKEN }}
        ISSUE_NUM: ${{ steps.scan-zap.outputs.issue_number }} ##gets the issue number
        REMEDIATION: ${{ steps.parse-json.outputs.remediation_body }} #gets the remediation body
      run: |
        if [ -n "$ISSUE_NUM" ]; then
          gh issue edit "$ISSUE_NUM" --body "$REMEDIATION"
        else
          echo "No issue number returned from ZAP scan step."
        fi
      
        
